name: Check Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pull-request:
    name: Check Pull Request - Call Workflows
    uses: thetote/workflows/.github/workflows/check-pr.yml@main
    secrets: inherit
