name: Publish Engineering Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  trigger-document-update:
    uses: thetote/workflows/.github/workflows/publish-docs.yml@main
    with:
      repositoryUrl: https://github.com/${{ github.repository }}.git
      ref: ${{ github.ref }}
    secrets: inherit
